version: '3.8'

services:
  web:
    build: ./pub
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pub/:/usr/src/pub/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blog
    ports:
        - "6543:5432"

volumes:
  dev_postgres_data:
