version: '3.8'

services:
  web:
    build: ./pub
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pub/:/usr/src/pub/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - ollama-setup
  
  db:
    image: postgres:16
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blog
    ports:
        - "6543:5432"
  
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    depends_on:
      - ollama-setup

  ollama-setup:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: |
      /bin/bash -c "
      # Start ollama in background
      /bin/ollama serve &
      # Wait for server to be ready
      sleep 5
      # Pull models if they don't exist
      /bin/ollama list | grep -q llama3.2 || /bin/ollama pull llama3.2
      # Keep container running briefly then exit
      sleep 2
      "

volumes:
  dev_postgres_data:
  ollama_data: