# Generated by Django 5.2.5 on 2025-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "per",
                    models.CharField(
                        blank=True,
                        choices=[("hour", "per hour"), ("project", "per project")],
                        help_text="e.g., per hour, per project",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "marketing_description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description for marketing purposes.",
                        null=True,
                    ),
                ),
                (
                    "marketing_title",
                    models.CharField(
                        blank=True,
                        help_text="A catchy title for marketing purposes.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "call_to_action",
                    models.CharField(
                        blank=True,
                        help_text="A call to action phrase.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
