# Generated by Django 5.2.6 on 2025-09-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments",
            field=models.ManyToManyField(blank=True, to="comments.comment"),
        ),
    ]
